### ISSUE TITLE
Error in configure

### ISSUE THREAD

**Issue by inode64** [AlphaNodes/additionals#1]
After configure plugin, it shows this error.
------------------------------------------------

NameError: uninitialized constant Emoji
/var/lib/redmine/plugins/additionals/lib/additionals.rb:19:in `block in <top (required)>'
/var/lib/redmine/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
 * ERROR: www-apps/redmine-3.3.3::inode64 failed (config phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 115:  Called pkg_config
 *   environment, line 4356:  Called die
 * The specific snippet of code:
 *           RAILS_ENV="${RAILS_ENV}" ${RUBY} -S rake db:migrate || die;
 *
 * If you need support, post the output of `emerge --info '=www-apps/redmine-3.3.3::inode64'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/redmine-3.3.3::inode64'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME="/etc/java-config-2/current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =redmine-3.3.3
 * The complete build log is located at '/var/tmp/portage/www-apps/redmine-3.3.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-apps/redmine-3.3.3/temp/environment'.
 * Working directory: '/var/lib/redmine'
 * S: '/var/tmp/portage/www-apps/redmine-3.3.3/work/redmine-3.3.3'

------------------------------------------------

Does that require https://github.com/github/gemoji?

**Comment by alexandermeindl** [comment]
Did you run bundle as in installation documentation  noticed? Or bundle update? It is required to run this plugin.
