### ISSUE TITLE
Specify according to requirements

### ISSUE THREAD

**Issue by CSCSxx** [AlphaNodes/additionals#106]
I use Additionals in a Docker environment alongside other plugins.
With every upgrade I have to comment out the call for "Dalli" in your gemfile, otherwise I get the following error message:

You specified: dalli (> = 0) and dalli (~> 2.7.0). Bundler cannot continue.
I think it would be an advantage if you also included the same specifications ...

**Comment by alexandermeindl** [comment]
Hi @CSCSxx,

Dalli is not in the Gemfile of this plugin. Maybe you mixed up it with another plugin?

**Comment by CSCSxx** [comment]
Ups....you are right, my failure ;)
