### ISSUE TITLE
Redmine 4.2.X - hide members in project memberbox doesn't work

### ISSUE THREAD

**Issue by ebergu78** [AlphaNodes/additionals#108]
- Redmine 4.2.0 + Additionals 2.0.23 o
- Redmine 4.2.0 + Additionals 3.0.2

En ambos casos los usuarios sin permiso para ver roles ocultos, pueden ver la lista completa de los miembros (usuarios y grupos) de un proyecto. Muestra todos los roles inclusive los que marqué como "ocultos"

**Comment by alexandermeindl** [comment]
This problem is fixed in Additionals Master for Redmine 4.2. Please try it and let me know, if it works for you.

**Comment by ebergu78** [comment]
Additionals Master ok!
