### ISSUE TITLE
Newly created dashboard crashes when trying to edit

### ISSUE THREAD

**Issue by hermannkm** [AlphaNodes/additionals#109]
After installation of plugin I created a dashboard which now is not saveable/deletable (e.g. when changing something) without crashing:

`
Page not found
The page you were trying to access doesn't exist or has been removed.
Back
`

**url:** 
`
https://redmine.klocker-mark.eu/dashboard.1
`

**Log:**

`
Started GET "/dashboards/1/edit" for 178.165.174.238 at 2021-07-03 13:36:12 +0200
Processing by DashboardsController#edit as HTML
  Parameters: {"id"=>"1"}
  Current user: admin (id=1)
  Rendering plugins/additionals/app/views/dashboards/edit.html.slim within layouts/base
  Rendered plugins/additionals/app/views/dashboards/_form.html.slim (18.5ms)
  Rendered plugins/additionals/app/views/dashboards/edit.html.slim within layouts/base (20.6ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (0.3ms)
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (1.8ms)
  Rendered plugins/additionals/app/views/additionals/_body_top.slim (0.2ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_scrum_tips.html.erb (2.1ms)
  Rendered plugins/redmine_drawio/app/views/redmine_drawio/_macro_dialog.html.erb (0.4ms)
  Rendered plugins/additionals/app/views/additionals/_body_bottom.html.slim (0.2ms)
  Rendered plugins/redmine_people/app/views/common/_people_select2_data.html.erb (0.4ms)
  Rendered plugins/redmine_people/app/views/common/_layout_bottom.html.erb (0.6ms)
Completed 200 OK in 87ms (Views: 58.4ms | ActiveRecord: 19.0ms)
Started PATCH "/dashboard.1" for 178.165.174.238 at 2021-07-03 13:36:18 +0200

ActionController::RoutingError (No route matches [PATCH] "/dashboard.1"):

actionpack (5.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.6) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.6) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.6) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
rack (2.2.3) lib/rack/content_length.rb:17:in `call'
railties (5.2.6) lib/rails/engine.rb:524:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
`

Versions:

```
Environment:
  Redmine version                4.2.1.stable.21007
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.13.0
  Git                            2.25.1
  Filesystem                     
Redmine plugins:
  additionals                    3.0.3-master
  dashboard                      1.0.11
  easy_gantt                     1.13
  easy_mindmup                   1.0
  easy_wbs                       1.5
  redhopper                      2.0.0
  redmine_checklists             3.1.19
  redmine_dmsf                   2.4.7
  redmine_drawio                 1.0.3
  redmine_ics_export             4.0.1.dev
  redmine_issue_dynamic_edit     0.7.2
  redmine_lightbox2              0.5.1
  redmine_monitoring_controlling 0.1.1
  redmine_people                 1.6.1
  redmine_wiki_sql               0.0.1
  scrum                          0.21.0
```

**Comment by alexandermeindl** [comment]
Hi @hermannkm 
can you try it without the other plugins? Maybe you find out the right plugin, which has a compatibility problem with additionals.

**Comment by hermannkm** [comment]
Hallo Alexander,

Ungerne, weil ich nicht genau weiß, ob ich Daten verliere, wenn ich die Plugins lösche (und dann wiederherstelle).
Gibt es keine andere Möglichkeit?
Hab inzwischen herausgefunden, dass ich Dashboards erstellen kann, aber nicht modifizieren, das gilt für alle, auch das Projekt-Dashboard, das ich inzwischen sehr schätze: endlich eine Wiki-Übersicht auf der Projektseite!!

Hermann

**Comment by alexandermeindl** [comment]
Hi @hermannkm,

if we don't know, which plugin causes problems, we cannot fix it. I think, if you do not uninstall the plugins, but just remove the directory, should quite good to test it.

**Comment by hermannkm** [comment]
Hi Alexander,

Very useful tip just to move the directories — didn’t know that. Now this way the culprit was found easily, your plugin is working if I delete just the „Dashboard“ plugin, all others do not interact.
So for now I will disable this one and will send a message to the developer.

Thank you,

Hermann

**Comment by alexandermeindl** [comment]
Hi @hermannkm,

I tried additionals plugins in latest version with the latest redmine_dashboard version and I cannot reproduce your problem. Can you try it with latest version again? Let me know, if you it works for you now.

**Comment by hermannkm** [comment]
Thank you for checking. Yes, I am now successfully running both plugins together.
