### ISSUE TITLE
Mails Comments on closed Tickets

### ISSUE THREAD

**Issue by SkunkerAG** [AlphaNodes/additionals#11]
Hi all,

According to the last post in The Request [Feature #13814](https://www.redmine.org/issues/13814) a functionality was added to [Redmine Tweaks](http://www.redmine.org/plugins/redmine_tweaks) now Redmine Tweaks redirects to here.

The function disallows to send a mail to a closed ticket.

Do you support such a function?

Thank You and best Regards,
Rene

**Comment by SkunkerAG** [comment]
Got it, it is about not commenting it. 
adding a comment via Mail still works, it would be nice, if it sends a no reply message.

**Comment by alexandermeindl** [comment]
You are right, it should not be possible to a comment an issue via mail. If I got some time, I'll integrate it (but this is not in the next weeks).

**Comment by alexandermeindl** [comment]
With my last commit to master, you can active freezed issue option. With this activated, it is not possible to add comments with API or mail. If the user has "edit closed issues", he can break this rule.
