### ISSUE TITLE
dashboard blocks cache

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#111]
Hello,

How it works if i want to use the same "data" (from sql request for example) in several blocks on the same dashboard ?
It can be possible (it's just to optimize requests) ? 

thanks

**Comment by alexandermeindl** [comment]
Hi @skalimer0 
this is already possible. See https://github.com/AlphaNodes/additionals/blob/master/app/models/dashboard_content.rb#L63 and https://github.com/AlphaNodes/additionals/blob/master/app/models/dashboard.rb#L298. For async_params use unique_params to create a unique cache key.

**Comment by skalimer0** [comment]
OK 
it's much more understanding for me

Thanks you for your return.

PS: Soon, I'll have a pull request...  ;)
