### ISSUE TITLE
 Mysql2::Error: Table 'dashboards' already exists

### ISSUE THREAD

**Issue by cowrycoin** [AlphaNodes/additionals#115]
Hello,

during the installation I get the error:

` Mysql2::Error: Table 'dashboards' already exists`

**Environment:**
  Redmine version                4.2.2.devel
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  6.1.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.7.14
  Mercurial                      5.8.1
  Git                            2.24.4
  Filesystem                     
**Redmine plugins:**
  redmine_agile                  1.6.1
  redmine_base_deface            1.8.1
  redmine_base_stimulusjs        1.1.1
  redmine_checklists             3.1.19
  redmine_contacts               4.3.4
  redmine_contacts_helpdesk      4.1.12
  redmine_contacts_invoices      4.2.5
  redmine_drawio                 1.1.3
  redmine_finance                2.1.7
  redmine_mermaid_macro          1.0.0
  redmine_multiprojects_issue    4.1.1
  redmine_people                 1.6.1
  redmine_products               2.1.2
  redmine_resources              1.0.5
  redmine_shortcuts              0.5.0
  redmine_subproject_collapse    0.0.1
  redmine_zenedit                2.0.1

**Comment by alexandermeindl** [comment]
Hi @cowrycoin,
did you get an install error before, which created the database table "dashboards"? Or do/did you use another plugins which uses database table "dashboards"?
As long as this table exists before installation _additionals_, this cannot work. If you 100% sure, no other plugin uses this table, you can drop it manually and try running  _additionals_ installation again.

**Comment by alexandermeindl** [comment]
Because of no further feedback, I close this issue. Feel free to reopen it, if required.
