### ISSUE TITLE
always_expose option for dashboard

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#121]
Hello,

I don't understand the function of : always_expose.

For me, i supposed it's to display this dashboard by default all the time where a user go to Overview of a project. But it's the last displayed dashboard who's used. It's just for displayed the name ?

It can be useful to add parameter to always return to a specific default dashboard for all users (included with another recently_id information) and if the user want to consult another one, he must select it in the status panel or dashboard menu.

Because if users go to the project before a project default dashboard creation by the dashboards manager for this project... (they have recently_id of the default projects dashboard (with no project_id)) .The creator must send mail to say to all off them to go to the new default dashboard.

Thanks.

**Comment by alexandermeindl** [comment]
Hi @skalimer0,

you are right, this was not easy to understand. I change to description with a better explanation.

This option means: If it is on, the dashboard name is always visible. If a user has only one dashboard, you can suppress displaying dashboard name, if it is disabled.
This option has only effect for displaying the dashboard name or not. Nothing else.

I hope, it is more clear now with the new string for it.
