### ISSUE TITLE
base deface error 

### ISSUE THREAD

**Issue by atopcu** [AlphaNodes/additionals#126]
Hello,
I am trying to install stable branch in to our instance.

giving below error during migration:

---

Bundler could not find compatible versions for gem "deface":
  In snapshot (Gemfile.lock):
    deface (= 1.5.3)

  In Gemfile:
    deface (= 1.5.3)

    additionals was resolved to 3.0.3, which depends on
      deface (= 1.8.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

---

redmine_base_deface is installed and updated.

What can I do?

Environment:
  Redmine version                4.2.1.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.5
  Environment                    production
  Database adapter               Mysql2

Best Regards,

**Comment by alexandermeindl** [comment]
Hi @atopcu 

remove redmine_base_deface, this is not required for Additionals. Additionals loads deface without this redmine_base_deface plugin.

**Comment by atopcu** [comment]
Thanks for quick answer.
My other plugins is using it.

**Comment by alexandermeindl** [comment]
Hi @atopcu 

no, I do not see any other option. We remove version information from deface to get better compatibility with other plugins. But if a plugin, as redmine_base_deface, define a version, this is not compatible with our plugin.

**Comment by alexandermeindl** [comment]
Hi @alexandermeindl,

I was wrong, additionals set version to deface '1.8.1'. If redmine_base_deface uses '1.8.1', too, it should work.

**Comment by atopcu** [comment]
Thank You so much.
This solved the issue.

2 Ara 2021 Per 11:42 tarihinde Alexander Meindl ***@***.***>
şunu yazdı:
