### ISSUE TITLE
Setting to disable FontAwesome

### ISSUE THREAD

**Issue by hertell** [AlphaNodes/additionals#13]
It would be a good idea to have a checkbox to disable FontAwesome. I personally think this font is horrible..
edit: quick fix => reverted back to redmine_tweaks

**Comment by alexandermeindl** [comment]
We love FontAwesome and there is no plan to implement an option to deactivate it. Just feel free, fork it and change yourself whatever you want ;)

**Comment by hertell** [comment]
This is a bit disturbing.. A plugin customizing  Redmine should not force to change the default font just because devs "love" it.. It's reminds me of people loving the "Comic Sans" font and using it on everything they produce...

**Comment by alexandermeindl** [comment]
Default font? Do you even know what FontAwesome does?

**Comment by hertell** [comment]
The only thing i know is what i see, and it looks ugly.

**Comment by alexandermeindl** [comment]
If now other plugin use it as Library, you only see one singe Icon in the admin area of it, see my picture of it. That all it does. If you have problem with it, just don't use this plugin.
<img width="208" alt="admin-menu" src="https://user-images.githubusercontent.com/205221/33114429-1c086cd6-cf5d-11e7-817b-6fb5e52a8ab8.png">

**Comment by hertell** [comment]
I wonder then why additionals changes all the fonts in redmine to something completely else? Removing this plugin restores the fonts to normal.

**Comment by alexandermeindl** [comment]
This should not be the case. Please try it with Redmine default theme and/or check you modifications in Redmine. As I already wrote, at the moment only one single icon is used. If it changes anything else in your Redmine, something went wrong. I cannot reproduce this behavior, you describe.
