### ISSUE TITLE
Updating with git problem

### ISSUE THREAD

**Issue by hermannkm** [AlphaNodes/additionals#131]
Sorry, probably a newbie question:
Upgrading (as I did some time ago) with _git pull_ throws

```
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

Any hint?

**Comment by alexandermeindl** [comment]
Hi @hermannkm,

we renamed "master" branch to "main". Try to make `git branch -m main && git pull`

**Comment by hermannkm** [comment]
Thank you for your information. I had to use the following procedure

```
git branch -u origin/main
git stash
git pull

```
AND I had to do this for _additional_tags_ too for my website to restart successfully.
_stashing_ was necessary in both cases.
