### ISSUE TITLE
Emoji assets installed in public/images/emojis instead of public/plugin_assets/additionals/images/emojis

### ISSUE THREAD

**Issue by gramakri** [AlphaNodes/additionals#138]
Emoji assets are copied into the public/images/emojis which may not be writable.

To give some context: On Cloudron, we run redmine in a readonly docker container. This means that only specific paths are writable. For plugin assets, this is `public/plugin_assets/`. This was reported in our forum [here](https://forum.cloudron.io/topic/7106/failure-installing-additionals-plugin-due-to-ro-filesystem).

The code  in `install_emoji_assets` writes into a directory outsite plugin_assets. Is this a bug or do redmine plugins expect to write there?

https://github.com/AlphaNodes/additionals/blob/55312e4fa591d1f6efb0f1cf1705c0200fbc4f70/lib/additionals/gemify.rb#L12 is the code in question. I guess that code should be writing into plugin_assets like https://github.com/AlphaNodes/additionals/blob/55312e4fa591d1f6efb0f1cf1705c0200fbc4f70/lib/additionals/gemify.rb#L33

**Comment by alexandermeindl** [comment]
With my last commit for main branch emojis are copied in a directory within plugin_assets. I suppose this solved your problem.

**Comment by gramakri** [comment]
@alexandermeindl thanks! the user reported on the forum that the issue is fixed with your latest commit
