### ISSUE TITLE
removing redmine_tweaks for upgrade to Additionals

### ISSUE THREAD

**Issue by ausghostdog** [AlphaNodes/additionals#14]
Hi,
We are currently in the process of upgrading our Redmine instance and Ruby to the latest versions, however, we have hit an issue in the removal of Redmine_tweaks. Simply removing the folder and raking the database fails. Or using the Redmine plugin removal method specifying the plugin name also fails.

is there another method to removing this plugin at all?

Sorry to post this here but I can not seem to contact you via the website as it says it is spam using your contact page and the page for the old redmine tweaks no longer accepts communication I also posted in https://www.redmine.org/boards/3/topics/54123
![image](https://user-images.githubusercontent.com/7588602/33103983-71015860-cf71-11e7-996b-d85cce24a504.png)

**Comment by alexandermeindl** [comment]
Just removing the plugin is directory is enough and restarting the application server. Nothing else is to do!

If this does not work for you, this could mean:

- you did not remove the plugin directory
- your system environment caches invalid information (ask your system administrator for this)
- you have another plugin installed, which requires redmine_tweaks (just remove all other plugins to test it)
- you have an modified/hacked Redmine version installed, which does not act as Redmine form redmine.org

Just do make sure, you get it right: there is nothing special to do for uninstalling redmine_tweaks.

**Comment by ausghostdog** [comment]
Well I solved it, clearing system cache did not help, what I ended up doing was after removing the addon I had a look at the error.log 

you need to allow write permissions for the file at path:
/opt/redmine/current/Gemfile.lock (Bundler::InstallError)

After checking the file the user had rw to it, after a bit of research I read on https://bundler.io/man/bundle-install.1.html that if a gem.lock file is present run bundle update and install and the server came back up so all good now.

**Comment by alexandermeindl** [comment]
Thanks for you feedback!
