### ISSUE TITLE
Some typos in the GUI (English)

### ISSUE THREAD

**Issue by ohuseyinoglu** [AlphaNodes/additionals#140]
Just noticed these during the first peek after install - not worth a pull request I guess, so reporting here:
- settings/plugin/additionals?tab=web "para**mt**ers" & "param**a**ters"
- settings/plugin/additionals?tab=rules "**Is** this function used in combination with" => If?

**Comment by alexandermeindl** [comment]
Hi @ohuseyinoglu 

thanks for reporting! Typos should be fixed in main branch.
