### ISSUE TITLE
Missing custom menu items in top menu since version 3.0.6

### ISSUE THREAD

**Issue by mmundi72** [AlphaNodes/additionals#149]
Hi Alphanodes team

We just installed the latest version of the additionals plugins - together with the latest version of the commercial plugins from Alphanodes.

Now I discovered that our custom top menu items are gone and reading the change log I saw that you removed this great feature in version 3.0.6. Why? It was great to have this included in additionals as there is no need for another plugin.

Can you pleases re-introduce this feature? We are using this now for some years and just removing such features without any real reason is a quite strange.

Thank you.
Mischa

**Comment by mmundi72** [comment]
Ok, we are not using the HRM plugin and just for the top menu this is quite an overkill.

**Comment by omiT84** [comment]
> Ok, we are not using the HRM plugin and just for the top menu this is quite an overkill.

I second this.
We are also using the custom menu feature.
We just found out it is missing.
I am really surprised this is removed.
Why not remove it from HRM and keep it in additionals?
It really is an additional feature, not an HRM feature right?

Anyone knows of a small alternative for this?

**Comment by whotopia** [comment]
Does anyone have any solutions to this?  It's a real shame this feature was removed.  Could it be recast as a separate plugin?  Has someone done this?
