### ISSUE TITLE
Hide in memberbox also for watcher

### ISSUE THREAD

**Issue by StephaneDavid74** [AlphaNodes/additionals#15]
The hide in memberbox option is nice to remove member from memberbox.
It would be nice to have it also for watcher.

This way, we can have a "user" profile that could see the other users for the same organization in memberbox in overview page, and in the watcher list. But they couldn't see the dev members.

While the project manager, with the "show in memberbox" option, could see everyone, both for watcher and memberfow

**Comment by alexandermeindl** [comment]
Nice idea. If I find time, I'll implement it - but the next couple of weeks are not realistic for this. But I am willing to accept a PR, if you can work on it.

**Comment by StephaneDavid74** [comment]
Sorry, I'm just a user I don't know how to make plugins. But no hurry, I just think it would interest several people, and nice to add when you have time.

**Comment by alexandermeindl** [comment]
This is now supported by Redmine 5 and with the latest additionals version (main branch).
