### ISSUE TITLE
Top menu items not working

### ISSUE THREAD

**Issue by pszafer** [AlphaNodes/additionals#16]
Hello,
I have new redmine installation.
I added top menu items (cache disabled) and it is not working.

In older version it is working without any problem.

Can you help me how to solve the problem/how to find some reasons it is failing?

**Comment by pszafer** [comment]
It showed up when I changed data of one user (different than logged in)...

**Comment by skalimer0** [comment]
I think... are you select permissions ?
I have the same result, but after selected all user role... The menu is add.

It's write : "Only members of selected roles will see this menu entry."

**Comment by pszafer** [comment]
I think I found reason for custom menu not working.
My user is admin user but I'm not participant of any project in my redmine installation. In that case custom menu not appear.
When I became member of one random project than I've been able to see custom menu.
Is it on purpose or is it some sort of bug?

**Comment by alexandermeindl** [comment]
This is the default Redmine behaviour. There is no other way to do it, because role permisssions are project related. If you have a role with a permission at least in one project, you get permission to view it.
