### ISSUE TITLE
You forgot about "edit_own_issues" permission

### ISSUE THREAD

**Issue by qawsed55** [AlphaNodes/additionals#163]
Hello, if user have permission `edit_own_issues`, but permission `edit_issues` for his role **is unset** - there are no statuses visible on sidebar.

**Comment by qawsed55** [comment]
I have changed from
`def memberships_new_issue_project_url(user, memberships, permission = :edit_issues)` 
<...>
`elsif permission == :edit_issues`

to
def memberships_new_issue_project_url(user, memberships, permission = :edit_issues | :edit_own_issues)
<...>
`elsif permission == :edit_issues | :edit_own_issues`

in `lib\additionals\helpers.rb`

and also here `test\functional\issues_controller_test.rb`
from:
`User.current.allowed_to?(:edit_issues, @project) | \`
to
```
     User.current.allowed_to?(:edit_issues, @project) | \
     User.current.allowed_to?(:edit_own_issues, @project) && \
```

and it works ok. I do not know Ruby (and programming at all), but it seems almost right.
As  temporary solution I think its ok!

**Comment by alexandermeindl** [comment]
Hi @qawsed55,

thanks for reporting this! It should be fixed with my last commit in main branch.

**Comment by alexandermeindl** [comment]
Let me know, if it does not work for you (you can reopen this issue)
