### ISSUE TITLE
Macros outside wiki

### ISSUE THREAD

**Issue by acosonic** [AlphaNodes/additionals#17]
Can I use macros on project page?

**Comment by alexandermeindl** [comment]
All not real related wiki macros you can use everywhere. Wiki related macros are e.g:
- last_updated_at
- last_updated_by
- recently_updated
- child_pages (from redmine core)

**Comment by alexandermeindl** [comment]
Documentation has been updated with scope information to all macros: https://additionals.readthedocs.io/en/latest/macros/

**Comment by acosonic** [comment]
But can they be used like here: Text for login page or Global sidebar ?

**Comment by alexandermeindl** [comment]
All plugins, except these macros above. All others you can use in login_page or global sidebar, or issues, or news, or comments, or .... 😄

**Comment by alexandermeindl** [comment]
I hope, you are satisfied with my answer. I close this issue now.
