### ISSUE TITLE
additionals is incompatible with redmine_editauthor plugin

### ISSUE THREAD

**Issue by vomus** [alphanodes/additionals#171]
Hi!
Just tried to install it on my 5.0.4 and found out that it is not compatible with redmine_editauthor. Can this be fixed?

docker-redmine-1  | rake aborted!
docker-redmine-1  | 
docker-redmine-1  | additionals plugin cannot be used with redmine_editauthor plugin.
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/redmine_plugin_kit-1.0.4/lib/redmine_plugin_kit/loader.rb:101:in `block in incompatible?'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/redmine_plugin_kit-1.0.4/lib/redmine_plugin_kit/loader.rb:100:in `each'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/redmine_plugin_kit-1.0.4/lib/redmine_plugin_kit/loader.rb:100:in `incompatible?'
docker-redmine-1  | /home/redmine/redmine/plugins/additionals/lib/additionals.rb:104:in `setup'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/redmine_plugin_kit-1.0.4/lib/redmine_plugin_kit/plugin_base.rb:14:in `setup!'
docker-redmine-1  | /home/redmine/redmine/plugins/additionals/lib/additionals/hooks/model_hook.rb:7:in `after_plugins_loaded'
docker-redmine-1  | /home/redmine/redmine/lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
docker-redmine-1  | /home/redmine/redmine/lib/redmine/hook.rb:66:in `each'
docker-redmine-1  | /home/redmine/redmine/lib/redmine/hook.rb:66:in `block in call_hook'
docker-redmine-1  | /home/redmine/redmine/lib/redmine/hook.rb:63:in `tap'
docker-redmine-1  | /home/redmine/redmine/lib/redmine/hook.rb:63:in `call_hook'
docker-redmine-1  | /home/redmine/redmine/lib/redmine/plugin_loader.rb:110:in `block in load'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
docker-redmine-1  | /home/redmine/redmine/config/environment.rb:16:in `<top (required)>'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:367:in `require_environment!'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
docker-redmine-1  | /home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
docker-redmine-1  | Tasks: TOP => redmine:plugins:migrate => environment
docker-redmine-1  | (See full trace by running task with --trace)
'

**Comment by alexandermeindl** [comment]
Hi @vomus,

this is not possible, because additionals provide same functionality. Why to you want to use redmine_editauthor, if you can change the author with additionals?

**Comment by alexandermeindl** [comment]
I close this because no further information was provided.
