### ISSUE TITLE
How to use the Query groups block？

### ISSUE THREAD

**Issue by popyy-hpo** [alphanodes/additionals#172]
I'm so glad to find this plugin,it's really awesome!

After installation, basically all functions can be used normally, except for this Query groups block, which I added to the project dashboard after creating several bug/support/feature items in the issue. 
However, it displays as shown below. 

![WX20231108-102841@2x](https://github.com/alphanodes/additionals/assets/59186555/d30cc14c-8cc0-4f1c-af94-b2713c2372ca)

I wonder if my use method is wrong, so that this can not be displayed normally? If so, can you tell me how to use this block correctly?

**Comment by ClaudiaMeindl** [comment]
Thank you for your message.
Regarding your Problem "No active counter available" the following.
The message indicates that no counter groups have been activated for display, yet.

The "Counter Group Dashboard block" you describe here, is part of the Reporting plugin, which comes with dashboard support, as well. So you need to go to the plugin settings of the Reporting plugin.
To do this, you must make the appropriate counter box group settings in the respective plugin area (/settings/plugin/redmine_reporting?tab=groups). Here you can:
* Create new counter groups of your choice and
* edit existing groups with regard to the display like:
  * On overview page
  * On project page
  * Visibility
  
Afterwards, custom queries must be assigned to the existing groups, depending on which ones you want to display there.
Kind regards
