### ISSUE TITLE
rake aborted?

### ISSUE THREAD

**Issue by canadabri** [alphanodes/additionals#174]
I am trying to configure my Redmine to fetch emails (pop3) and I am getting an error that I am not sure what to do with.  

The info returned shows:
```
<path>.../plugins/additionals/lib/additionals/wiki_formatting/common_mark/emoji_filter.rb:7: warning: already initialized constant Additionals::WikiFormatting::CommonMark::EmojiFilter::IGNORED_ANCESTOR_TAGS
<path>.../plugins/additionals/lib/additionals/wiki_formatting/common_mark/emoji_filter.rb:7: warning: previous definition of IGNORED_ANCESTOR_TAGS was here

<path>.../additionals/lib/additionals/wiki_formatting/common_mark/smiley_filter.rb:7: warning: already initialized constant Additionals::WikiFormatting::CommonMark::SmileyFilter::IGNORED_ANCESTOR_TAGS
<path>.../plugins/additionals/lib/additionals/wiki_formatting/common_mark/smiley_filter.rb:7: warning: previous definition of IGNORED_ANCESTOR_TAGS was here
rake aborted!
```

So I am not certain if this is being caused by something in the additionals plugin or not, but the rake is aborted following those warnings.

Has anyone seen anything like this?   

Redmine 5.1.1
additionals 3.1.0

**Comment by canadabri** [comment]
This can be dismissed or closed.  There was something wrong but the command completes now (I suspect certain characters in the password are not valid when used in the rake task).  Changing the password to something simpler did let the rake task complete, however the emails are still not processed.  I tested without any alphanodes plugins installed and the same issue is happening.

**Comment by alexandermeindl** [comment]
Hi @canadabri, ok thanks for your feedback.
