### ISSUE TITLE
URL on custom fields not in new window

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#18]
Hello,

If we want to open external URL in a new window, the URIs used in custom fields are open always in the same window. no target="_blank" are add or no rel="noreferrer" like in the top menu.

Thanks

**Comment by alexandermeindl** [comment]
The problem is, that Redmine does not set css class "external" with custom field link format. This css class is required, that the external URL handling works with this plugin. At the moment I have no solution for it.

**Comment by alexandermeindl** [comment]
With the latest Redmine version, css class "external" is set. This solved this issue 👍
