### ISSUE TITLE
Hide in memberbox does not seem to be effective

### ISSUE THREAD

**Issue by BrunoSpy** [AlphaNodes/additionals#19]
Version : 2.0.6
I created a new role with "hide in memberbox" right.
But this role and its members is still displayed in the list. Is there something specific to do ?

**Comment by alexandermeindl** [comment]
This role should not have the permission "Show hidden roles in member box ".  No other setting is required. Of course, user with admin permissions will always see it (as it is default in Redmine).

**Comment by BrunoSpy** [comment]
Ok, I was testing with an "admin" user. Sorry to have bothered you.
