### ISSUE TITLE
Installing for Redmine 5.1 request

### ISSUE THREAD

**Issue by Saylrman64** [alphanodes/additionals#190]
Hello,

I've been trying to get this installed for some time now and it seems as though I completely missed out.
It took us a month to get migrated to Redmine 5.1 but now we find this only supports Redmine >6.

I find no there are no Releases and only Tags.

It is possible to run on Redmine 5.1 and if so, which Tag would I select?
We are on:
  Redmine version                5.1.4.stable.23201
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]

Because every version of additionals depends on redmine_plugin_kit >= 0
  and redmine_plugin_kit >= 1.0.3 depends on deface = 1.9.0,
  every version of additionals requires deface = 1.9.0 or redmine_plugin_kit >= 0, < 1.0.3.
Because redmine_plugin_kit >= 1.0.2, < 1.0.3 depends on deface = 1.8.2
  and redmine_plugin_kit < 1.0.2 depends on deface = 1.8.1,
  redmine_plugin_kit < 1.0.3 requires deface = 1.8.1 OR = 1.8.2.
Thus, every version of additionals requires deface = 1.8.1 OR = 1.8.2 OR = 1.9.0.
So, because Gemfile depends on additionals >= 0
  and Gemfile depends on deface = 1.6.2,
  version solving has failed.
=====================

I appreciate your time and thank you.

**Comment by alexandermeindl** [comment]
Hi @Saylrman64,
I just read, that use use Ruby 3.0, this is not supported. You should use Ruby 5.1.x or Ruby 5.2.x for Redmine 5.1.

**Comment by Saylrman64** [comment]
Hey Alex,

Thank you for you prompt reply.

As main branch is simply listed as "Default" I did not assume it was dev., as there is a "Stable" I should've. I didn't intend to waste anyone's time.

I walked backwards through the Tags and at 3.0.9 it installed for me. This was with no other plugins to cause conflicts regarding redmine_plugin_kit.

Again, thank you for your time.
