### ISSUE TITLE
issue() macro is using non-absolute links which breaks links in notification email with that macro

### ISSUE THREAD

**Issue by borismedovnik** [AlphaNodes/additionals#21]
The newly introduced {{issue(1234)}} macro is extremely useful. However, we have noticed that when we get  email notifications about comments in issues, this macro renders correctly in email, however the URL itself is relative (i.e. "/issue/1234"), instead of being absolute (with domain name).

This makes it impossible to quickly click the issue link and see details.

Unfortunately I'm not familiar with the redmine codebase, but looking at the code I have a guess that the problem happens in https://github.com/AlphaNodes/additionals/blob/e0879aec062fffa933fd3973d1f2230c0c5b0c78/lib/additionals/helpers.rb#L22 as it passes only_path = true to link_to. If this is indeed the problem, maybe you could pass an additional only_path param to render_issue_macro_link() to pass-through to link_to.

Maybe I'm wrong and the bug happens somewhere else.

**Comment by alexandermeindl** [comment]
Thanks for reporting it! I push a fix to the master branch.

**Comment by borismedovnik** [comment]
Thanks for a quick fix, Alexander!

I checked out master and the fix helped for native Redmine notifications. However notifications that I receive from redmine_mentions plugin (https://github.com/arkhitech/redmine_mentions ) still have the same problem (broken links).

I found that this happens due to the way you check the controller here:
https://github.com/AlphaNodes/additionals/blob/master/lib/additionals/helpers.rb#L22

I fixed it by changing:
`only_path = controller_path != 'mailer'`
to
`only_path = controller_path != 'mailer' && controller_path != 'mention_mailer'`

Now it works for me perfectly. However I don't think this is a good way to fix it, since we can't anticipate plugins that are going to use mail notifications. Instead I think it's better to check if it's inherited from ActionMailer::Base or something like that.

**Comment by alexandermeindl** [comment]
Hi borismedovnik, thanks for your feedback. I commit a slightly better solution.  I don't like this kind of solutions, but I could find another way to get the context - which is required to set relative or absolute paths. All plugins I check used as last part _mailer in controller name, so this solution should work for the moment ;)
