### ISSUE TITLE
Problems on install with gemoji

### ISSUE THREAD

**Issue by janekska** [AlphaNodes/additionals#23]
I did like written in docs, but:
```
.../usr/local/redmine# bundle exec gemoji extract public/images/emoji
bundler: failed to load command: gemoji (/usr/local/bin/gemoji)
```
"gem install gemoji" was successful.

What could be wrong?

**Comment by alexandermeindl** [comment]
Did you run it on macOS Sierra or later? This command cannot be used with linux, because the emojis are exported from MacOS libraries (which are not available on other OS)

**Comment by janekska** [comment]
Hm, and what can I use under Linux Ubuntu?

**Comment by alexandermeindl** [comment]
I dont know, most emojis came from Apple. If you find a solution to get emojis with linux, please let me know.
