### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by gsal** [AlphaNodes/additionals#24]
Hi:

First of all, forgive me but I am a total ruby newbie and don't even plan on learning ruby, I just want to use Redmine; having said that...

I am following the instructions [here](https://additionals.readthedocs.io/en/latest/) for installing Additionals; and, after cloning the project, I am having a hard time with the very next line:
```
bundle install --without development test
```
If I type it just like from Redmine top directory, it does not find the Gemfile that was just written under plugins/additionals.

If I pass --gemfile=./plugins/additionals/Gemfile, then I get the following output:
```
$ bundle install --without development test --gemfile=./plugins/additionals/Gemfile
Fetching gem metadata from https://rubygems.org/............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 12.3.1
Using concurrent-ruby 1.0.5
Using i18n 1.0.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5

Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
An error occurred while installing activesupport (5.2.0), and Bundler cannot continue.
Make sure that `gem install activesupport -v '5.2.0'` succeeds before bundling.

```
The first time I saw the above error, I went ahead and installed `activesupport` into the Ruby installation, so, it should already be there. 

Using:
```
$:~/redmine-3.4.4-3/
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
$ gem --version 
2.7.6
$ bundle --version 
Bundler version 1.7.8
```
I own the Redmine directory
I do not own the ruby installation directory (no write permission, I have to use a different user id to install stuff there)

Questions:
why does the error keeps coming up?
Where is bundle trying to install stuff? within Redmine directory? or into Ruby installation directory?

Please help. 

Thanks.

**Comment by alexandermeindl** [comment]
I looks like you use Redmine Master branch and not Redmine version 3.4.4. ActiveSupport 5.2.0 is not used with Redmine 3.4.4. Also ruby 2.5.1 is not used with bundler in your setup, because you get a message activesupport requires Ruby version >= 2.2.2.

It looks like your main problem is, that Redmine is not using the right Gemfile. In a normal setup you just run "bundle install" in REDMINE_ROOT_DIR, that's it. You do not need to specify or run bundler with Redmine plugins individually.

Let' me know, if you already fixed the problem.

**Comment by gsal** [comment]
No, I have not solved the problem; but, I am now a bit out of touch since I have not looked into this issue since then.  I will re-visit and see if your comments come handy, this time around. 

thanks

**Comment by alexandermeindl** [comment]
I close this issue for now. If have further questions related to this issue, feel free and reopen it again.
