### ISSUE TITLE
Wiki sidebar doesn't work with custom wiki start page

### ISSUE THREAD

**Issue by danielvijge** [AlphaNodes/additionals#27]
In lib/additionals/patches/wiki_patch.rb the wiki homepage name (ID) is hard coded to 'Wiki'. However, in the project settings this can be configured to a different page. If a page with the name 'Wiki' doesn't exist, the custom wiki sidebar is not shown.

To solve it:
lib/additionals/patches/wiki_patch.rb:24 from
`@sidebar ||= find_page('Wiki', with_redirect: false)`
to
`@sidebar ||= find_page(project.wiki.start_page, with_redirect: false)`

**Comment by alexandermeindl** [comment]
Thanks for reporting it! I fixed it in master branch.
