### ISSUE TITLE
Issue attribute 'Time in status' not updated when using sidebar links

### ISSUE THREAD

**Issue by Spectropeter** [AlphaNodes/additionals#28]
I'm using Additionals together with the RedmineUp Agile plugin and have the following problem:

When I change the status of an issue via the sidebar links like:
.../issues/2274/change_status?new_status_id=5

The issue attribute "Time in status" is not updated.
I don't how the attribute is stored or calculated, but its working fine, when the issue status is changed 'the normal way'.

Here is an example, how the attribute is displayed in the agile plugin:
https://www.redmineup.com/pages/help/agile/time-in-status

Any idea?

**Comment by alexandermeindl** [comment]
Hi Spectropeter,

thanks for reporting this! I fixed it with my last commit in master branch. Let me know, if it is not working as expected.
