### ISSUE TITLE
How do I use angular_gantt with additionals?

### ISSUE THREAD

**Issue by lindaxsotherby** [AlphaNodes/additionals#3]
My apologies for this is actually not an issue regarding your code. I am just not proficient enough in ruby to decipher from the hints in the documentation on how to use angular_gantt with additionals in redmine. Could you please help? Will appreciate it. I use redmine 3.2.1.

**Comment by alexandermeindl** [comment]
Hi, no problem.

Just put in your Redmine template:

```
<% content_for :header_tags do %>
  <%= additionals_library_load(:angular_gantt) %>
<% end %>

```

This will load/include angular gantt libraries and you can use it in our template. The main advantage is, that angular_gantt is provided through Additionals and is installed AND loaded just once, so more plugins can use it without loading multiple angular_gantt libraries at the same time.

I hope, this helps you a little bit.

**Comment by lindaxsotherby** [comment]
Thank you. I managed to include the scripts into redmine's native template. Unfortunately, I admit I had the preconception that I would be able to replace redmine's native gantt javascript code just by doing that. Apparently, I have a lot of code tinkering to do to achieve that. Thank you by the way for this very fine plugin.

**Comment by alexandermeindl** [comment]
Thanks, I appreciate that
