### ISSUE TITLE
Edit button disapeared

### ISSUE THREAD

**Issue by AndKar63** [AlphaNodes/additionals#30]
Hi, after installing your plugin in Redmine 3.4. and configuring the new feature "If 'Assignee' is unchanged and the issue status changed from x to y, than the author is assigned to the issue" the Edit button on Issue page disappeared for status y. Editing issue is still anabled throught context menu on issue list (right mouse button).  
Return to previous settings didn't restore it. 

Thanks for your help!

**Comment by AndKar63** [comment]
Supplement.
It may be caused by the "issue status on sidebar" setting rather than settings for assignee, I think. I can change the status without using edit feature, but can't see edit button on the issue page at all. The role have edit issues and add notes rights. Notes I can add only by editting from shortcut menu of the issue list.

![issue status on sidebar](https://user-images.githubusercontent.com/43443516/45951270-23089500-c003-11e8-9ff2-320f2260bab9.PNG)
![edit button disappered](https://user-images.githubusercontent.com/43443516/45951277-2865df80-c003-11e8-9977-b3be79af0458.PNG)
![edit function on issue](https://user-images.githubusercontent.com/43443516/45951280-2ac83980-c003-11e8-9ef4-babee83d2ec2.PNG)

**Comment by alexandermeindl** [comment]
Hi AndKar63,

thanks for your report! Do you have any other plugins installed?

**Comment by alexandermeindl** [comment]
Oh, I see what you mean. This bug is fixed in the current master brunch. In the stable version this bug is not fixed. Next stable version should be available next month.
