### ISSUE TITLE
Problem with plugin install

### ISSUE THREAD

**Issue by kallenp** [AlphaNodes/additionals#31]
We have a problem with the "Redmine Additionals Plugin” install
[plugin.log](https://github.com/AlphaNodes/additionals/files/2405036/plugin.log)
[plugin.log](https://github.com/AlphaNodes/additionals/files/2405037/plugin.log)

.
Can we ask for help and information what might be wrong ?

Log file attached.

==================================================================
Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Cvs                            1.12.13
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.4.9
  custom_users_as_assignees      0.0.2
  extra_queries                  2.3.4
  global_roles                   2.2.3
  group_of_authors_filter        0.0.1
  redmine_agile                  1.4.6
  redmine_contacts               4.1.2
  redmine_contacts_helpdesk      3.0.9
  redmine_custom_css             0.1.7
  redmine_image_clipboard_paste  3.3.0
==================================================================

Best regards,
Petr Kallen

**Comment by alexandermeindl** [comment]
Because of no further feedback I close this issue.

**Comment by kallenp** [comment]
ok
