### ISSUE TITLE
Change Author - Disabled Users

### ISSUE THREAD

**Issue by neisenberg** [AlphaNodes/additionals#33]
When a user has the 'change author' permission and they are editing an issue that was authored by a now-disabled user, the default entry in the author field is set to the current user (<<Me>>).  This has the effect that editing an issue edited by a disabled user often results in unintentionally changing the authorship of that issue.

Note that for this to happen, the editing user must have explicit membership in the project to which the issue belongs.  This issue cannot be reproduced, for instance, by testing as a superuser unless that superuser is enumerated in the projects membership list.

The expected behavior is that the authorship should be preserved by default, unless the editing user explicitly changes it.

**Comment by alexandermeindl** [comment]
Your right, I'll take a look at it.

**Comment by alexandermeindl** [comment]
The problem should be fixed in master branch.

**Comment by alexandermeindl** [comment]
Fix is in stable version, too.
