### ISSUE TITLE
Performance of _html_head.html.slim

### ISSUE THREAD

**Issue by dktcoding** [AlphaNodes/additionals#36]
I found some performance issues when rendering `_html_head.html.slim`:

<details><summary>Debug Log</summary><pre>
SQL (1.3ms)  SELECT `members`.`id` AS t0_r0, `members`.`user_id` AS t0_r1, `members`.`project_id` AS t0_r2, `members`.`created_on` AS t0_r3, `members`.`mail_notification` AS t0_r4, `projects`.`id` AS t1_r0, `projects`.`name` AS t1_r1, `projects`.`description` AS t1_r2, `projects`.`homepage` AS t1_r3, `projects`.`is_public` AS t1_r4, `projects`.`parent_id` AS t1_r5, `projects`.`created_on` AS t1_r6, `projects`.`updated_on` AS t1_r7, `projects`.`identifier` AS t1_r8, `projects`.`status` AS t1_r9, `projects`.`lft` AS t1_r10, `projects`.`rgt` AS t1_r11, `projects`.`inherit_members` AS t1_r12, `projects`.`default_version_id` AS t1_r13, `projects`.`default_assigned_to_id` AS t1_r14, `projects`.`intouch_settings` AS t1_r15 FROM `members` INNER JOIN `projects` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 10 AND `projects`.`status` != 9
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 50
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 729
  Role Load (0.9ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 15
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 102
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 714
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 740
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 56
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 60
  Role Load (0.7ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 104
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 216
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 225
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 767
  Role Load (0.7ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 743
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 318
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 319
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 317
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 312
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 772
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 360
  Role Load (0.7ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 775
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 442
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 448
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 656
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 454
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 768
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 486
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 491
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 497
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 501
  Role Load (0.7ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 505
  Role Load (0.7ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 511
  Role Load (0.9ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 515
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 519
  Role Load (0.9ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 744
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 753
  Role Load (0.7ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 747
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 750
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 563
  Role Load (1.0ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 566
  Role Load (0.9ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 523
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 542
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 545
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 571
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 577
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 583
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 756
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 762
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 610
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 616
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 622
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 628
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 759
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 643
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 720
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 770
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 735
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 791
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 795
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 801
  Role Load (0.6ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 810
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 816
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 817
  Role Load (0.5ms)  SELECT DISTINCT `roles`.* FROM `roles` INNER JOIN `member_roles` ON `roles`.`id` = `member_roles`.`role_id` WHERE `member_roles`.`member_id` = 824
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (136.0ms)
~~~
</pre></details><br>

As you can see from the debug logs the culprit seems to be the custom menus (which I'm actually not even using), when removing this:

~~~ruby
- if User.current.try(:hrm_user_type_id).nil?
  - user_roles = User.current.memberships.includes(:project).collect(&:roles).flatten.uniq
  - Additionals::MAX_CUSTOM_MENU_ITEMS.times do |i|
    - additionals_custom_top_menu_item(i, user_roles)
~~~

Rendering time goes from this (~100ms):

~~~
Processing by ProjectsController#index as HTML
  Current user: fede (id=10)
  Rendering projects/index.html.erb within layouts/base
  Rendered projects/index.html.erb within layouts/base (31.4ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.5ms)
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (97.7ms)
  Rendered plugins/additionals/app/views/additionals/_content.html.slim (0.2ms)
  Rendered plugins/redmine_zxcvbn/app/views/hooks/redmine_zxcvbn/_view_layouts_base_body_bottom.html.erb (0.2ms)
  Rendered plugins/additionals/app/views/additionals/_body_bottom.html.slim (0.1ms)
Completed 200 OK in 166ms (Views: 112.5ms | ActiveRecord: 43.7ms)
~~~

To this (~1ms):

~~~
Processing by ProjectsController#index as HTML
  Current user: fede (id=10)
  Rendering projects/index.html.erb within layouts/base
  Rendered projects/index.html.erb within layouts/base (26.1ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.4ms)
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (0.6ms)
  Rendered plugins/additionals/app/views/additionals/_content.html.slim (0.2ms)
  Rendered plugins/redmine_zxcvbn/app/views/hooks/redmine_zxcvbn/_view_layouts_base_body_bottom.html.erb (0.2ms)
  Rendered plugins/additionals/app/views/additionals/_body_bottom.html.slim (0.1ms)
Completed 200 OK in 62ms (Views: 46.4ms | ActiveRecord: 7.8ms)
~~~

**Comment by alexandermeindl** [comment]
Hi dktcoding,

thank you for reporting this!

I did some improvements about this:

with 5000 repeats of custom menu integration
* 22.543200   0.779947  23.323147 ( 23.865270) - before without and with menu items
* 0.235706   0.001123   0.236829 (  0.236911) - without menu items
* 4.503395   0.122037   4.625432 (  5.261305) - with menu items

The problem with menu items is, that all roles of the current user has to be searched, and this is very expensive.

But I think the results now are much better then before. What do you think?

**Comment by dktcoding** [comment]
Those numbers look much better!

> The problem with menu items is, that all roles of the current user has to be searched, and this is very expensive.

Yeahp, I get the problem here.
 
I just checkout the master branch, and it worked amazingly (~1ms):

```
Processing by ProjectsController#index as HTML
  Current user: fede (id=10)
  Rendering projects/index.html.erb within layouts/base
  Rendered projects/index.html.erb within layouts/base (31.9ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.5ms)
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (0.8ms)
  Rendered plugins/additionals/app/views/additionals/_content.html.slim (0.2ms)
  Rendered plugins/redmine_zxcvbn/app/views/hooks/redmine_zxcvbn/_view_layouts_base_body_bottom.html.erb (0.3ms)
  Rendered plugins/additionals/app/views/additionals/_body_bottom.html.slim (0.1ms)
Completed 200 OK in 73ms (Views: 53.6ms | ActiveRecord: 9.2ms)
```

I created a custom menu and the rendering took ~5ms:

```
Processing by ProjectsController#index as HTML
  Current user: fede (id=10)
  Rendering projects/index.html.erb within layouts/base
  Rendered projects/index.html.erb within layouts/base (30.6ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.5ms)
  Rendered plugins/additionals/app/views/additionals/_html_head.html.slim (5.1ms)
  Rendered plugins/additionals/app/views/additionals/_content.html.slim (0.2ms)
  Rendered plugins/redmine_zxcvbn/app/views/hooks/redmine_zxcvbn/_view_layouts_base_body_bottom.html.erb (0.3ms)
  Rendered plugins/additionals/app/views/additionals/_body_bottom.html.slim (0.2ms)
Completed 200 OK in 76ms (Views: 54.1ms | ActiveRecord: 11.5ms)
```

Thanks for the quick reply and the fix!

**Comment by alexandermeindl** [comment]
No problem and thanks for reporting it! ;)
