### ISSUE TITLE
Change status in sidebar links don`t send emails

### ISSUE THREAD

**Issue by radoslavius** [AlphaNodes/additionals#37]
Hi,
if I change status with sidebar links, redmine don`t send emails to users (subscribers, solver). Is it an intent? I think it is an unexpected behavior and therefore an error.
Thanks

**Comment by alexandermeindl** [comment]
You are right. This should work the same way, like changing status with by editing an issue. I'll check it.

**Comment by alexandermeindl** [comment]
You are right, I can reproduce it. I am working on the fix...

**Comment by alexandermeindl** [comment]
Hi radoslavius,
I commited a fix to master. Now it should work as expected.

**Comment by radoslavius** [comment]
Yes, it looks good. Thanks for the fast response
