### ISSUE TITLE
Conflict with 3.4.'s new feature: default assignee

### ISSUE THREAD

**Issue by lublasco** [AlphaNodes/additionals#4]
Hi,

as soon as I install your plugin in Redmine 3.4. the new feature "[Default assignee per project](http://www.redmine.org/issues/482#change-80171)" disappears.

Could you please review the code to solve this issue?

Thanks for your help!

**Comment by alexandermeindl** [comment]
Thank you for reporting this! You are right with that, I'll provide a fix for it today.

**Comment by alexandermeindl** [comment]
With my last commit this bug should be fixed. Let me know, if you have problems with it yet.

**Comment by lublasco** [comment]
Solved! Thank you for the fix!
