### ISSUE TITLE
main page not opened after installed plugin

### ISSUE THREAD

**Issue by pink-sky** [AlphaNodes/additionals#44]
![K-20190330-741419](https://user-images.githubusercontent.com/49026448/55275565-62ee6300-532b-11e9-9acb-c3db2d5c11cc.png)
![K-20190330-742260](https://user-images.githubusercontent.com/49026448/55275587-98934c00-532b-11e9-8352-2622f25e7500.png)

and gem list

> *** LOCAL GEMS ***

actioncable (5.2.2, 5.0.2)
actionmailer (5.2.2, 5.0.2)
actionpack (5.2.2, 5.0.2)
actionpack-xml_parser (2.0.1)
actionview (5.2.2, 5.0.2)
activejob (5.2.2, 5.0.2)
activemodel (5.2.2, 5.0.2)
activerecord (5.2.2, 5.0.2)
activestorage (5.2.2)
activesupport (5.2.2, 5.0.2)
addressable (2.6.0)
akami (1.2.0)
arel (9.0.0, 7.1.4)
ast (2.4.0)
atomic (1.1.14)
awesome_nested_set (3.1.4)
awesome_print (1.8.0)
aws-sdk (2.9.0)
aws-sdk-core (2.9.0)
aws-sdk-resources (2.9.0)
aws-sigv4 (1.0.0)
axiom-types (0.1.1)
bcrypt-ruby (3.1.1)
better_errors (2.5.1)
bigdecimal (default: 1.3.2)
bindex (0.5.0)
binding_of_caller (0.8.0, 0.7.3)
bluecloth (2.2.0)
brakeman (4.5.0)
builder (3.2.3)
bundler (default: 1.17.3, 1.14.6)
byebug (9.1.0)
charlock_holmes (0.6.9.4)
codeclimate-engine-rb (0.4.1)
coderay (1.1.2)
coercible (1.0.0)
coffee-rails (4.2.1)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
columnize (0.9.0)
commander (4.4.7)
concurrent-ruby (1.1.5, 1.1.4, 1.0.5)
crack (0.4.3)
crass (1.0.4)
css_parser (1.7.0)
csv (3.0.4)
daemon_controller (1.2.0)
daemons (1.2.4)
dalli (2.7.10)
debug_inspector (0.0.3)
debugger-linecache (1.2.0)
deface (1.3.2)
descendants_tracker (0.0.4)
did_you_mean (1.1.0)
diff-lcs (1.3)
equalizer (0.0.11)
equatable (0.5.0)
erubi (1.8.0)
erubis (2.7.0)
escape_utils (1.2.1)
eventmachine (1.2.3)
execjs (2.7.0)
faraday (0.15.4, 0.11.0)
faraday_middleware (0.11.0.1)
fast_stack (0.1.0)
fast_xor (1.1.1)
fast_xs (0.8.0)
ffi (1.9.18)
flay (2.12.0)
flog (4.6.2)
gemoji (3.0.0)
gherkin (4.1.1)
github-markdown (0.5.3)
globalid (0.4.2, 0.4.0)
gyoku (0.4.6)
haml (5.0.4)
haml-rails (2.0.0)
hashie (1.2.0)
highline (2.0.1)
hike (2.1.3)
hiredis (0.4.5)
hoe (3.16.0)
hoe-bundler (1.3.0)
hoe-debugging (1.3.0)
hoe-gemspec (1.0.0)
html2haml (2.2.0)
htmlentities (4.3.4)
http_parser.rb (0.5.3)
httparty (0.14.0)
httpauth (0.2.0)
i18n (0.8.1, 0.7.0)
ice_nine (0.11.2)
iconv (1.0.3)
invisible_captcha (0.12.0)
io-console (default: 0.4.6)
jaro_winkler (1.5.2)
jbuilder (2.5.0)
jmespath (1.3.1)
jquery-rails (4.2.2)
json (default: 2.0.4, 1.8.6)
jwt (0.1.8)
kwalify (0.7.2)
launchy (2.4.3)
libv8 (3.16.14.15 x86_64-linux)
liquid (2.6.3)
listen (3.0.8)
logger (1.3.0)
loofah (2.2.3, 2.0.3)
mail (2.7.1, 2.6.4)
marcel (0.3.3)
memcache-client (1.8.5)
method_source (0.9.2, 0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.3)
mini_magick (4.7.0)
mini_mime (1.0.1)
mini_portile (0.6.0)
mini_portile2 (2.4.0, 2.3.0)
minitest (5.11.3, 5.10.1)
multi_json (1.12.1, 1.5.0)
multi_xml (0.6.0)
multipart-post (2.0.0)
mysql2 (0.5.2, 0.4.2)
necromancer (0.4.0)
net-ldap (0.16.1)
net-telnet (0.1.1)
nio4r (2.3.1, 2.0.0)
nokogiri (1.10.1, 1.8.1)
oauth (0.4.7)
oj (3.7.11, 2.18.5)
omniauth (1.1.4)
openssl (default: 2.0.9)
ox (2.10.0)
parallel (1.16.2)
parser (2.6.2.0)
passenger (5.1.2)
pastel (0.7.2)
path_expander (1.0.3)
pg (0.18.0.pre20141117110243, 0.15.1)
polyglot (0.3.5)
posix-spawn (0.3.13)
power_assert (0.4.1)
psych (3.1.0, default: 2.2.2)
public_suffix (3.0.3)
puma (3.8.2)
racc (1.4.14)
rack (2.0.6, 2.0.1)
rack-openid (1.4.2)
rack-test (1.1.0, 0.6.3)
rails (5.2.2, 5.0.2)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.3, 2.0.2)
rails-html-sanitizer (1.0.4, 1.0.3)
railties (5.2.2, 5.0.2)
rainbow (3.0.0)
rake (12.3.2, 12.0.0, 0.8.7)
rake-compiler (1.0.3)
rb-fsevent (0.9.8)
rb-inotify (0.9.8)
rbpdf (1.19.8)
rbpdf-font (1.19.1)
rdiscount (2.2.0.1)
rdoc (default: 5.0.0, 4.0.1)
redcarpet (3.4.0, 3.0.0)
RedCloth (4.3.2)
redis (3.3.3)
redmine-installer (2.2.7)
redmine_crm (0.0.42)
redmine_extensions (0.3.00, 0.2.16)
reek (5.3.2)
ref (2.0.0)
request_store (1.0.5)
require_patch (0.3.3)
rexical (1.0.5)
rinku (2.0.2)
rmagick (2.16.0, 2.15.4)
roadie (3.4.0)
roadie-rails (1.3.0)
rouge (3.3.0)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rubocop (0.66.0)
ruby-hmac (0.4.0)
ruby-openid (2.3.0)
ruby-progressbar (1.10.0)
ruby_parser (3.13.1)
rubycritic (4.0.2)
rubygems-update (3.0.3)
rubyzip (1.2.2)
safe_yaml (1.0.4)
sass (3.4.23)
sass-rails (5.0.6)
sdoc (0.4.2)
sexp_processor (4.12.0)
simple_enum (2.3.2)
simple_oauth (0.1.9)
slim (4.0.1)
slim-rails (3.2.0)
slim_lint (0.16.1)
slop (4.4.1)
spring (2.0.1)
spring-watcher-listen (2.0.1)
sprockets (3.7.2, 3.7.1)
sprockets-rails (3.2.1, 3.2.0)
sqlite3 (1.3.13)
sqlite3-ruby (1.3.3)
subexec (0.2.3)
sysexits (1.2.0)
temple (0.8.1)
test-unit (3.2.3)
therubyracer (0.12.3)
thin (1.7.0)
thor (0.20.3, 0.19.4, 0.18.1)
thread_safe (0.3.6)
tilt (2.0.9, 2.0.6)
timers (4.3.0)
togglv8 (1.2.1)
treetop (1.6.8)
tty-color (0.4.3)
tty-cursor (0.5.0)
tty-progressbar (0.15.1)
tty-prompt (0.16.1)
tty-reader (0.3.0)
tty-screen (0.6.5)
tty-spinner (0.8.0)
tty-which (0.4.0)
turbolinks (5.0.1)
turbolinks-source (5.0.0)
twitter-stream (0.1.16)
tzinfo (1.2.5, 1.2.3)
tzinfo-data (1.2016.10)
uglifier (3.0.4)
unicode-display_width (1.5.0)
uuidtools (2.1.5)
virtus (1.0.5)
web-console (3.4.0)
websocket-driver (0.7.0, 0.6.5)
websocket-extensions (0.1.3, 0.1.2)
will_paginate (3.1.7)
wisper (2.0.0)
xmlrpc (0.2.1)
yajl-ruby (1.3.0)
zip-zip (0.3)

i try v2-stable and master both installed..
but main page not open..

i don't find error source file. what location?

i installed version bitnami redmine for linux 4.0.2

**Comment by pink-sky** [comment]
![K-20190330-745240](https://user-images.githubusercontent.com/49026448/55275647-4bfc4080-532c-11e9-84ae-24ddb3fdba01.png)

**Comment by alexandermeindl** [comment]
Did you use the installation instruction https://github.com/AlphaNodes/additionals/blob/master/docs/index.rst#installation and are you sure that your webserver restartet? Strange, that your error screen does not list additionals plugin in it.

**Comment by miniream** [comment]
![](https://user-images.githubusercontent.com/49026448/55275587-98934c00-532b-11e9-8352-2622f25e7500.png)

my redmine is bitnami redmine 4.0.2...
package installed

redmine version 4.0.2
ruby version 2.4.5

**Comment by alexandermeindl** [comment]
As I already wrote, your redmine and ruby version looks good. I suppose your webserver didn't restart. Try to stop it or reboot your system. And make sure you run bundle, as described in installation instruction.

**Comment by alexandermeindl** [comment]
Because of no further feedback I close this issue. Please feel free and reopen it, if you have problems, yet.
