### ISSUE TITLE
Subprojects in Projects macro

### ISSUE THREAD

**Issue by mdima** [AlphaNodes/additionals#45]
Hello, 
   now the projects macro does not consider subprojects... that means that you see the subprojects at the same level of the main projects. 
It would be nice if the subprojects would be somehow indented OR an option to hide them. 

Thanks!
Michele

**Comment by alexandermeindl** [comment]
Hierarchy support for projects macro is now implemented.

**Comment by mdima** [comment]
Thanks! :)
