### ISSUE TITLE
Recursion Crash when going to settings page BUG

### ISSUE THREAD

**Issue by MatCat** [AlphaNodes/additionals#46]
I just installed on a fresh 4.0.3 install of Redmine, and when I go to Administration -> Settings I get a recursive issue:

SystemStackError (stack level too deep):

plugins/redmine_wiki_extensions/lib/wiki_extensions_helper_patch.rb:22:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:14:in `heads_for_wiki_formatter_with_additionals'
plugins/redmine_wiki_extensions/lib/wiki_extensions_helper_patch.rb:22:in `heads_for_wiki_formatter'
plugins/redmine_wiki_extensions/lib/wiki_extensions_helper_patch.rb:22:in `heads_for_wiki_formatter'
plugins/additionals/lib/additionals/patches/formatting_helper_patch.rb:14:in `heads_for_wiki_formatter_with_additionals'

... (Just keeps going on for hundreds of lines)

**Comment by alexandermeindl** [comment]
Please try it without wiki_extensions plugins. This looks like this is the problem.

**Comment by alexandermeindl** [comment]
This problem was fixed with 5275a921f55a9c21e9a5e49.
