### ISSUE TITLE
closing issue with open sub issues is needed?

### ISSUE THREAD

**Issue by pva** [AlphaNodes/additionals#47]
I've installed additionals with redmine 3.4.10 and found that it still has the following option:

configurable issue rules
    closing issue with open sub issues

Yet it looks like this functionality exists in redmine itself:
https://www.redmine.org/issues/10989

It looks like it's better to remote this feature for >=redmine-3.4.10.

**Comment by alexandermeindl** [comment]
Hi pva, thanks for reporting this!

I'll check it. And you are right, this should be removed, if this is Redmine itself.

**Comment by alexandermeindl** [comment]
Done, changes are in Master branch.
