### ISSUE TITLE
Plugins incompatible

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#48]
In redmine 4.x

The plugin : https://github.com/haru/redmine_wiki_extensions (0.9.0) is incompatible with additionals (infinite loop on issue edit for example)...

**Comment by jmtemmos** [comment]
I confirm that drawio and wiki extention plugins are unfortunatelly incompatible with additionals in redmine 4.0

**Comment by alexandermeindl** [comment]
With my last commit in master branch drawio should work with additionals.

**Comment by jmtemmos** [comment]
Perfect. Working fine now. Thanks @alexandermeindl

**Comment by alexandermeindl** [comment]
Hi @skalimer0,
with master branch there should be no more problems compatibility problem with redmine_wiki_extensions. Please try latest additionals version for testing.

**Comment by alexandermeindl** [comment]
This fix is now in stable branch.
