### ISSUE TITLE
Change Author - Sort Order

### ISSUE THREAD

**Issue by mmundi72** [AlphaNodes/additionals#5]
We have just installed the new version of additionals (a great plugin by the way!) and we like the possiblity to change the author of a issue.

But I discovered that the list of users is strangely sorted (not the same order as the assignee field). 

Details see this picture:

![changeauthor-sortorder](https://user-images.githubusercontent.com/7224922/28667818-5f146332-72cd-11e7-821c-ac0572ef2db1.jpg)

---
Environment:
  Redmine version                3.2.3.stable.15483
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               Mysql2

**Comment by alexandermeindl** [comment]
Thank you for the praise!

You are right, I fixed the sort order with my last commit.
