### ISSUE TITLE
Compatibility Issue - redmine_auto_watch plugin

### ISSUE THREAD

**Issue by rohitthakral** [AlphaNodes/additionals#50]
Here we go. Another compatibility issue. 

additionals plugin cannot be used with redmine_auto_watch plugin'

**Comment by alexandermeindl** [comment]
Thats right, you cannot use redmine_auto_watch with additionals. Reason is, additionals provides same functionality, but an improved version :)

**Comment by rohitthakral** [comment]
:-) Problem solved. Thanks Alexander!!

**Comment by alexandermeindl** [comment]
Glad to hear!
