### ISSUE TITLE
Redmine performance issue

### ISSUE THREAD

**Issue by bilel-kedidi** [AlphaNodes/additionals#6]
Hello,
i use redmine with multiple plugins on it. i have hundreds of projects on it and when installing this plugin, i found that this plugin or redmine tweaks will consume up to 2 sec to load the page..
before i got loading a page within 2.5 sec. in project_issues_path.
now i got it with 4.5 sec
Thanks for the help

**Comment by alexandermeindl** [comment]
Hi, thanks for reporting this! 
Do you use any column in issue list, which shows wiki macros (e.g. description)? Additionals comes with lots of macros, maybe this is the reason for slower request results.

**Comment by alexandermeindl** [comment]
Can you provide me more information, which columns you use? Which features of Additionals do you use? (topmenu, macros, etc).
I did some tests with deactivate some parts of Additionals patches, but I got always almost the same performance (with around 1.000 projects and 50.000 issues).

**Comment by alexandermeindl** [comment]
Because I got no further feedback, I close this issue.
