### ISSUE TITLE
Macro errors in email updates

### ISSUE THREAD

**Issue by sphereweb83** [AlphaNodes/additionals#69]
Hello,

I use some of macros available for knowledgebase such ask `{{category()}}` and `{{article()}}`. While they work find in tickets, when i receive email updates about those tickets, i get the following errors:

`Error executing the category macro (undefined method `category_path' for #<#<Class:0x00007fa18c089960>:0x00007fa18c17e118> Did you mean? category_url)`

and 

`Error executing the article macro (undefined method `article_path' for #<#<Class:0x000055fd81fb5840>:0x000055fd8136a568> Did you mean? article_url)`

Any ideas what causes this?

**Comment by alexandermeindl** [comment]
These macros are not provided by additionals plugin. Please contact  knowledgebase developers to get help for that.
