### ISSUE TITLE
Allow child_pages in project context

### ISSUE THREAD

**Issue by camlafit** [AlphaNodes/additionals#72]
Hello

In project page, could be nice to take in consideration project context as same level wiki behavior. 
Purpose it's to list all wiki page directly from any project page,

Actually we get ```Error executing the child_pages macro (With no argument, this macro can be called from wiki pages only.)``` If we set in settings/plugin/additionals?tab=projects > Project guide : {{child_pages}}

**Comment by alexandermeindl** [comment]
child_pages macro is provided by Redmine itself - this is not an additionals macro.

**Comment by camlafit** [comment]
Hello

Oh my mistake we can close then :)
Sorry to be confused.
