### ISSUE TITLE
Redmine 4.1.x

### ISSUE THREAD

**Issue by konpega** [AlphaNodes/additionals#74]
What should be done to use this plugin in Redmine 4.1.0-8. 
When I saw >= 4.0.x, I thought that it is working :(

**Comment by alexandermeindl** [comment]
Hi  @konpega,
What is your question? I do not understand, what you want.

Current additionals version supports Redmine version  4.0 or newer, this means Redmine 4.1.x is included.

**Comment by konpega** [comment]
I applied the install proceduree but redmine collapsed and I reinstalled redmineplusagile 4.1.0-8 again. Now I am afraiding to install again.

**Comment by alexandermeindl** [comment]
So, can we close this issue?

If you need more help I need information about your ruby version, your Redmine Version, if there are other action plugins? Did you follow [installation instruction]( https://github.com/AlphaNodes/additionals#installation)? If yes, did occur errors by this? If yes, post error messages here.

**Comment by konpega** [comment]
I strictly followed the steps. Here is my prog info.
![image](https://user-images.githubusercontent.com/61666724/80840357-cd946100-8c05-11ea-9d30-fb0c2e9c7eb2.png)

**Comment by alexandermeindl** [comment]
If you used installation instruction from additionals, you should be fine with your ruby version. Git master does not support your ruby version anymore.

I need the error message you got, to provide you more help. See error log or startup problems. Any error message you got, I need to see to give you more information.

You can also try to run your Redmine without the other plugins. Maybe there is a conflict with another plugin.

**Comment by alexandermeindl** [comment]
I close this issue, because no more feedback has been provided.
