### ISSUE TITLE
How to disable the time_entry_patch

### ISSUE THREAD

**Issue by EvilBMP** [AlphaNodes/additionals#75]
Hi,

I needed to install the additionals plugin, because we use redmine git hosting and they set this plugin as requirement in their latest releases.

But after installing additionals many of my collegues are not able to log their time anymore, if another collegue already closed an issue (before the other collegue finished to log the time). So where can I disable this patch? I didn't find any checkbox regarding this "feature".

Thanks in advance.

**Comment by alexandermeindl** [comment]
Hi @EvilBMP,

please check your role permissions for time entries, there is a new permission available named "Log time on closed issues". Activate it and your problem should be solved.

<img width="765" alt="role_permission" src="https://user-images.githubusercontent.com/205221/80595711-7cc61200-8a25-11ea-8625-50bed04be17c.png">

**Comment by EvilBMP** [comment]
Thx for the hint. Didn't find any information about that in the manual. 👍
