### ISSUE TITLE
bootstrap-datepicker.en.min.js not found

### ISSUE THREAD

**Issue by danlittlejohn** [AlphaNodes/additionals#8]
My browser is looking for an "en" version of datepicker, but there is not one in locales

File not found: /support/plugin_assets/additionals/javascripts/locales/bootstrap-datepicker.en.min.js

**Comment by alexandermeindl** [comment]
Thanks for reporting it! Which language do use use in Redmine (setting in your user profile)?

**Comment by alexandermeindl** [comment]
Let me know, if it works with my last change. If not, I need to know, which language you use.

**Comment by danlittlejohn** [comment]
It is set to English (en).  The error indicates that there is no bootstrap-datepicker.en.min.js in the locale directory.

**Comment by danlittlejohn** [comment]
The change you made looks like it has fixed the problem.  Thanks!

**Comment by alexandermeindl** [comment]
I am glad to hear that! No problem.
