### ISSUE TITLE
Stack Level too Deep on wiki pages with redmine_wiki_extensions

### ISSUE THREAD

**Issue by rroseselavy42** [AlphaNodes/additionals#80]
Hey folks,

on Redmine 4.1.1 with Rails 5.2.4.2 and Ruby 2.6.3 I'm seeing an infinite loop with the redmine wiki extension. I'm not sure which plugin is at fault (if any fault) but starting here. 

When going to a wiki page where both plugins are active you end up in an infinite loops between:
plugins/additionals/lib/additionals/patches/wiki_controller_patch.rb:23:in `respond_to_with_additionals'
plugins/redmine_wiki_extensions/lib/wiki_extensions_wiki_controller_patch.rb:42:in `respond_to'

in additionals that is:
``` ruby 
      module InstanceMethods
        def respond_to_with_additionals(&block)
          if @project && @content
            if @_action_name == 'show'
              additionals_include_header
              additionals_include_footer
            end
          end
          respond_to_without_additionals(&block)
        end
```

in wiki extensions that is:
``` ruby 
  def respond_to(&block)
    if @project and WikiExtensionsUtil.is_enabled?(@project) and @content
      if (@_action_name == 'show')
        wiki_extensions_include_header
        wiki_extensions_add_fnlist
        wiki_extensions_include_footer
      end
    end
    super(&block)
  end
```

**Comment by alexandermeindl** [comment]
Hi @rroseselavy42,
thanks for reporting this! I fixed it this compatibility problem with my last commit.

**Comment by rroseselavy42** [comment]
can confirm working

**Comment by alexandermeindl** [comment]
Stable version released with this fix.
