### ISSUE TITLE
"Don't know how to build task 'redmine:additionals:seed" error

### ISSUE THREAD

**Issue by ffuue** [AlphaNodes/additionals#81]
Trying to install the plugin, but on `bundle exec rake redmine:additionals:seed RAILS_ENV=production` command receive `Don't know how to build task 'redmine:additionals:seed'`. What it may be happens?

Environment:

-   Redmine version                4.1.1.stable
-   Ruby version                   2.5.1-p57 (2018-03-29) [x86_64-linux-gnu]
-   Rails version                  5.2.4.2
-   Environment                    production
-   Database adapter               PostgreSQL
-   Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
-   Mailer delivery                smtp

SCM:

-   Git                            2.17.1
-   Filesystem        

             
Redmine plugins:

-   redmine_agile                  1.5.4

**Comment by alexandermeindl** [comment]
Hi @ffuue 

thanks for reporting this! I fixed installation instruction, there is no more seed task ;)

Greetings,
alex

**Comment by alexandermeindl** [comment]
Stable version released with this fix.
