### ISSUE TITLE
NoMethodError (undefined method `content_project=' for nil:NilClass):

### ISSUE THREAD

**Issue by nobless** [AlphaNodes/additionals#82]
When opening a project, im getting:

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

production.log:

Started GET "/projects/XXXXXX" for 188.X.X.X at 2020-08-24 09:11:19 +0000
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"XXXX"}
  Current user: tomas@xxxxxxxxx (id=26)
Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.3ms)

NoMethodError (undefined method `content_project=' for nil:NilClass):

plugins/additionals/lib/additionals/patches/projects_controller_patch.rb:39:in `find_dashboard'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by alexandermeindl** [comment]
Hi @nobless,

can you provide me more information about what you did after installing/updating to the latest additionals version? Did you delete a dashboard? Or did you change the default dashboard?

**Comment by nobless** [comment]
Thanks for fast solution, it worked with /projects/ANY-PROJECT-ID/dashboards/new. 

Recreated all the dashboards one by one on all projects.

**Comment by nobless** [comment]
* Dashboards were not deleted.
* Default dashboard was not changed.
* Yes.
* Used master branch 2020/08/22

**Comment by alexandermeindl** [comment]
Hi @nobless,

thanks for your feedback. Just as a note: if you create a new dashboard for a project and you leave the project blank, this dashboard is used as default dashboard for all projects. You don't need to create dashboards for all projects, if the content of a dashboard should be the same.

**Comment by alexandermeindl** [comment]
Hi @nobless,

I found the case, which caused your problem:

It was possible to change project_id for the project system default dashboard. This should not be possible for this special dashboard.

I fixed this problem with my last commit. Please update to the latest version to prevent getting same problems again.
