### ISSUE TITLE
Dashboard "Query: Issues" error on projects with helpdesk plugin

### ISSUE THREAD

**Issue by valentinab25** [AlphaNodes/additionals#85]
Hello

We have installed the latest version of the additionals plugin and are trying out the project dashboards. 
We are using the Redmine Helpdesk plugin on some of our projects ( https://www.redmineup.com/pages/plugins/helpdesk ). The plugin adds helpdesk related fields on issues.
Dashboards with "Query: Issues" block receive an error if there are any issues that are filtered :
`An error occurred while executing dashboard block issuequery_4 and has been logged. Please report this error to your Redmine administrator`

The error in log:
```
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.571397 #113]  INFO -- : Started GET "/projects/nanyt/dashboard_async_blocks?block=issuequery__4&dashboard_id=2&unique_key=d06e6ce1489a989db88d770e3f60a1af1f83a5984cc7a6dd40b9861ca5f94c92" for 10.42.129.235 at 2020-10-22 11:46:26 +0200
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.572361 #113]  INFO -- : Processing by DashboardAsyncBlocksController#show as */*
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.572413 #113]  INFO -- :   Parameters: {"block"=>"issuequery__4", "dashboard_id"=>"2", "unique_key"=>"d06e6ce1489a989db88d770e3f60a1af1f83a5984cc7a6dd40b9861ca5f94c92", "project_id"=>"nanyt"}
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.579975 #113]  INFO -- :   Current user: valentina (id=19783)
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.791157 #113]  INFO -- :   Rendered issues/_list.html.erb (173.0ms)
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.791257 #113]  INFO -- :   Rendered plugins/additionals/app/views/dashboards/blocks/_query_list.html.slim (207.0ms)
10/22/2020 12:46:27 PME, [2020-10-22T11:46:26.791352 #113] ERROR -- : Invalid dashboard block for issuequery__4: undefined method `helpdesk_ticket_source_icon' for #<#<Class:0x0000561f40e4d9e0>:0x00007efc289f76f0>
10/22/2020 12:46:27 PMDid you mean?  helpdesk_ticket_url
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.791924 #113]  INFO -- :   Rendering plugins/additionals/app/views/dashboards/block_error.html.slim
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.792270 #113]  INFO -- :   Rendered plugins/additionals/app/views/dashboards/block_error.html.slim (0.3ms)
10/22/2020 12:46:27 PMI, [2020-10-22T11:46:26.792427 #113]  INFO -- : Completed 200 OK in 220ms (Views: 0.8ms | ActiveRecord: 55.5ms)
```
 
The method is defined here:  redmine_contacts_helpdesk/app/helpers/helpdesk_helper.rb 

Is there any way for us to include it so the dashboards could be generated using the issue fields created by the plugin?

Thanks,
Valentina

**Comment by valentinab25** [comment]
Error:
![error](https://user-images.githubusercontent.com/30239069/96872654-94ce9980-147c-11eb-97d6-fb2db7800a18.png)
Log:
[errorlog.txt](https://github.com/AlphaNodes/additionals/files/5422828/errorlog.txt)

**Comment by alexandermeindl** [comment]
Hi Valentina,

thanks for reporting this problem. With my last commit to master branch, you should be able to use helpdesk columns in dashboard blocks.

Please let me known, if this works for you!

**Comment by valentinab25** [comment]
It works, thank you!

**Comment by Sir-Will** [comment]
@valentinab25 I like the redmine theme on your screenshot. Which theme is that if you don't mind?

**Comment by valentinab25** [comment]
@Sir-Will  We are using our theme https://github.com/eea/taskman.redmine.theme/ which is a fork of https://github.com/mrliptontea/PurpleMine2 with javascript/css customizations.

**Comment by Sir-Will** [comment]
Ah, thank you.
