### ISSUE TITLE
Plugin Installation on Railsinstaller with ruby 2.3

### ISSUE THREAD

**Issue by hunainafarrukh** [AlphaNodes/additionals#89]
I would like to know how should i install it on Railsinstaller with ruby 2.3.3 and rails 5.1. it is showing an error. Please help.

**Comment by alexandermeindl** [comment]
Hi @hunainafarrukh,

Ruby 2.3.3 is not supported by this plugin, see https://github.com/AlphaNodes/additionals#requirements
