### ISSUE TITLE
Error undefined method safe_load

### ISSUE THREAD

**Issue by sanste78** [AlphaNodes/additionals#9]
Hello,

I have `error: NoMethodError: undefined method safe_load for Psych:Module` when execute `bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

I don't find the solution.

Thank for your help

**Comment by alexandermeindl** [comment]
Which Redmine version, Ruby version and other plugins do you use?

**Comment by sanste78** [comment]
Hello,

The informations:

Environment:
  Redmine version                3.4.0.stable
  Ruby version                   2.0.0-p648 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.7.14
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_banner                 0.1.2
  redmine_issue_badge            0.0.6

*** LOCAL GEMS ***

actionmailer (4.2.8)
actionpack (4.2.8)
actionpack-xml_parser (1.0.2)
actionview (4.2.8)
activejob (4.2.8)
activemodel (4.2.8)
activerecord (4.2.8)
activesupport (4.2.8)
addressable (2.5.2)
arel (8.0.0, 6.0.4)
bigdecimal (1.3.2, 1.2.0)
builder (3.2.3)
bundler (1.15.4, 1.7.8)
coderay (1.1.2)
concurrent-ruby (1.0.5)
connection_pool (2.2.1)
crass (1.0.2)
css_parser (1.6.0)
deface (1.2.0)
erubis (2.7.0)
gemoji (3.0.0)
globalid (0.4.0)
htmlentities (4.3.4)
i18n (0.8.6, 0.7.0)
invisible_captcha (0.9.3)
io-console (0.4.6, 0.4.2)
jquery-rails (3.1.4)
json (2.1.0, 1.7.7)
loofah (2.1.1, 2.0.3)
mail (2.6.6)
mime-types (3.1)
mime-types-data (3.2016.0521)
mimemagic (0.3.2)
mini_portile2 (2.3.0, 2.1.0)
minitest (5.10.3)
mysql2 (0.4.9)
net-http-persistent (2.8)
net-ldap (0.16.0, 0.12.1)
nokogiri (1.6.8.1)
passenger (5.1.8)
polyglot (0.3.5)
protected_attributes (1.1.4)
psych (2.0.0)
public_suffix (2.0.5)
rack (1.6.8)
rack-openid (1.4.2)
rack-test (0.7.0, 0.6.3)
rails (4.2.8)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.3, 1.0.8)
rails-html-sanitizer (1.0.3)
railties (4.2.8)
rainbow (2.2.2)
rake (12.1.0, 0.9.6)
rbpdf (1.19.3)
rbpdf-font (1.19.1)
rdoc (4.0.0)
redcarpet (3.4.0)
request_store (1.3.2, 1.0.5)
rmagick (2.16.0)
roadie (3.2.2)
roadie-rails (1.1.1)
ruby-openid (2.7.0, 2.3.0)
sprockets (3.7.1)
sprockets-rails (3.2.1)
thor (0.20.0, 0.19.1)
thread_safe (0.3.6)
tzinfo (1.2.3)

Thank

**Comment by alexandermeindl** [comment]
Thanks for the info. You have an old Ruby version installed, which is not official support by Additionals. Maybe this is the problem - automatic tests only runs for Ruby 2.2.x, 2.3.x and 2.4.x.  Because you already use Redmine 3.4.x, I would recommend you to use Ruby 2.4.x and give it a try.

**Comment by alexandermeindl** [comment]
I did some tests with redmine_banner and redmine_issue_badge. I did't get your error with it, so your problem is most likely your ruby version.

**Comment by sanste78** [comment]
Thank, I try to update Ruby Version

**Comment by alexandermeindl** [comment]
Any news on this? Can we close this issue?

**Comment by alexandermeindl** [comment]
I close this issue for now, because no more feedback was coming.
