### ISSUE TITLE
Write new blocks

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#93]
Hello,

Can you explain quickly how we can create blocks in another plugin and include them in your dashboard system.

It's very interesting feature.

Thanks

**Comment by ClaudiaMeindl** [comment]
Thank you for your message.
We have implemented a section for developers into the plugin documentation to support you with this:: https://additionals.readthedocs.io/en/latest/dashboards/#developer-information
Thanks.

**Comment by skalimer0** [comment]
Thanks. it's very useful
Example with git_hosting is enough to understand.
