### ISSUE TITLE
New plugins with new dashboard blocks

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#95]
Hello,

I want create new block in my plugin.
I watch GitHosting example and i have something to execute. OK 👍 

But, now, i must put my methods in dashboards_helper.rb of Additionals plugins to execute action like your feed's block with dashboard_feed_catcher or dashboard_feed_title.

How can i put my method in my own plugins ? how patch dashboards_helper ?

thanks and good job.

**Comment by skalimer0** [comment]
I tried to patch projects_controller and dashboard_async_blocks_controller to include my own Helper... i tried to call my own Helper in html.slim file....

On each test, the result is the same : "undefined method" 

For information... I'm rails and ruby newbie... and i don't find solution for now.

**Comment by alexandermeindl** [comment]
Hi @skalimer0,
I am glad you found your solution. Just for info:
- for asynchronous blocks your helper should go to DashboardAsyncBlocksController
- for non-asynchronous blocks your helper should got to ProjectsController and/or WelcomeController
