### ISSUE TITLE
Dashboard's block for My Page

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#96]
Hello,

Do you  have possibility to add new block on MyPage ?

I found for Projet and Welcome page but not for that page.

Thanks

**Comment by alexandermeindl** [comment]
Hi @skalimer0,

no, this is not supported by additionals plugin.

**Comment by skalimer0** [comment]
It will be a very good feature for a 3.1.0 version ;)

**Comment by alexandermeindl** [comment]
This will not be happen, because there is a lot of features incompatible for my_page, e.g. asynchronous loading. Additionals dashboards  is more than a (better) replacement for my pages.

**Comment by skalimer0** [comment]
Ok

I think to remove My Page link and use Welcome Dashboard to make custom My Page functionality
