### ISSUE TITLE
Add chartjs matrix plugins 

### ISSUE THREAD

**Issue by skalimer0** [AlphaNodes/additionals#98]
Hello,

Can you add charjs matrix plugin ? like datalabels plugin or colorschemes plugin
https://github.com/kurkle/chartjs-chart-matrix

I could be useful to make priority matrix or risks matrix on dashboards.

Thanks

**Comment by skalimer0** [comment]
OK, i found 
https://d3plus.org/examples/d3plus-matrix/getting-started/
on d3plus.

So.... if you want :D

**Comment by skalimer0** [comment]
Doh!

d3plus graph don't be render in dashboard widget... nothing appear... no error in javascript console.

With this example https://d3plus.org/examples/d3plus-matrix/getting-started/

i make dashboard block in html.slim file just with add `= additionals_load_d3plus`

I have Javascript Error : TypeError: "Matrix" is not a constructor

With d3plus librairy at https://cdn.jsdelivr.net/npm/d3plus@2 : no javascript error.

I have matrix render OK on one html file example, but in dashboard block's my block is empty.

**Comment by skalimer0** [comment]
With a quick test, charjs-chart-matrix, i have a chart on my dashboard's block.

**Comment by skalimer0** [comment]
Just to show, matrix in action with blocks

![example](https://user-images.githubusercontent.com/8110622/112496019-b366f280-8d84-11eb-8859-0cb0c46517ab.png)

**Comment by alexandermeindl** [comment]
Matrix was added to main branch.
